export const SKILL_ASSESSMENT_SECONDS_PER_ITEM = 75;

export const DETERMINISTIC_SKILL_ITEMS = [
  {
    id: 'html-form-submit-semantic',
    skill: 'HTML',
    prompt: 'A form has a primary action that submits user input. Which element is the best default choice for that action?',
    choices: ['<div role="button">Submit</div>', '<button type="submit">Submit</button>', '<a>Submit</a>', '<span onclick="submit()">Submit</span>'],
    correctChoice: 1,
    explanation: 'A submit button has native semantics, keyboard behavior, and form integration.',
  },
  {
    id: 'html-accessible-image-alt',
    skill: 'HTML',
    prompt: 'A product card image communicates meaningful product information. What should its alt attribute contain?',
    choices: ['An empty string', 'A keyword-stuffed SEO description', 'A concise description of the image content', 'The file name of the image'],
    correctChoice: 2,
    explanation: 'Meaningful images need concise alternative text that communicates the same useful information.',
  },
  {
    id: 'css-grid-responsive-cards',
    skill: 'CSS',
    prompt: 'Which CSS grid declaration is most appropriate for a responsive card grid that fills available width without fixed breakpoints?',
    choices: [
      'grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));',
      'grid-template-columns: 240px 240px 240px;',
      'float: left;',
      'position: absolute;',
    ],
    correctChoice: 0,
    explanation: 'auto-fit with minmax creates responsive tracks that wrap based on available space.',
  },
  {
    id: 'css-box-sizing-border-box',
    skill: 'CSS',
    prompt: 'Why do many production CSS resets apply box-sizing: border-box globally?',
    choices: [
      'It makes margin part of the element width.',
      'It includes padding and border in declared width calculations.',
      'It disables flexbox shrinking.',
      'It improves JavaScript execution speed.',
    ],
    correctChoice: 1,
    explanation: 'border-box makes sizing more predictable because padding and borders are included in width and height.',
  },
  {
    id: 'javascript-event-loop-microtasks',
    skill: 'JavaScript',
    prompt: 'In JavaScript, when a resolved Promise callback and a setTimeout callback are both queued, which normally runs first?',
    choices: ['The setTimeout callback', 'The Promise microtask callback', 'They run at the same time', 'The browser chooses randomly'],
    correctChoice: 1,
    explanation: 'Promise callbacks run in the microtask queue before the next macrotask such as setTimeout.',
  },
  {
    id: 'javascript-duplicate-submit-guard',
    skill: 'JavaScript',
    prompt: 'A user double-clicks a checkout button and two API requests are sent. Which frontend guard is most appropriate?',
    choices: ['Reload the page after click', 'Disable or lock the action while the request is pending', 'Use localStorage for the response', 'Wrap the button in a div'],
    correctChoice: 1,
    explanation: 'A pending-state guard prevents duplicate client submissions and should be paired with server idempotency.',
  },
  {
    id: 'typescript-discriminated-union',
    skill: 'TypeScript',
    prompt: 'Which TypeScript model best represents loading, success, and error request states without many nullable fields?',
    choices: [
      'type State = any',
      'type State = { loading?: boolean; data?: Data; error?: string }',
      'A discriminated union with a status field',
      'A class with all properties optional',
    ],
    correctChoice: 2,
    explanation: 'Discriminated unions model each state explicitly and enable safe narrowing.',
  },
  {
    id: 'typescript-type-narrowing',
    skill: 'TypeScript',
    prompt: 'What is the main benefit of checking if ("error" in result) before reading result.error?',
    choices: ['It minifies the bundle', 'It narrows the union type safely', 'It converts strings to numbers', 'It disables runtime exceptions automatically'],
    correctChoice: 1,
    explanation: 'Property checks can narrow union members so TypeScript knows which fields are available.',
  },
  {
    id: 'react-key-reconciliation',
    skill: 'React',
    prompt: 'Why should React list keys be stable identifiers instead of array indexes when rows can be reordered?',
    choices: [
      'Stable keys help React preserve the correct component identity.',
      'Indexes always make rendering faster.',
      'Keys are only used for CSS selectors.',
      'Keys are sent to the backend automatically.',
    ],
    correctChoice: 0,
    explanation: 'Stable keys let React reconcile list items without mixing state between reordered rows.',
  },
  {
    id: 'react-effect-cleanup',
    skill: 'React',
    prompt: 'A component starts an interval in useEffect. What should the effect return?',
    choices: ['The interval id as a number', 'A cleanup function that clears the interval', 'A JSX element', 'A Promise'],
    correctChoice: 1,
    explanation: 'Effects that create subscriptions, timers, or listeners should clean them up on dependency changes or unmount.',
  },
  {
    id: 'node-secret-boundary',
    skill: 'Node.js',
    prompt: 'Why should a production app call third-party AI APIs from a Node backend instead of a browser React component?',
    choices: ['Browsers cannot make HTTP requests', 'It protects secrets and centralizes validation/rate limits', 'Node renders CSS faster', 'React cannot parse JSON'],
    correctChoice: 1,
    explanation: 'The server protects API keys and gives one place for validation, quotas, logging, and abuse controls.',
  },
  {
    id: 'node-nonblocking-io',
    skill: 'Node.js',
    prompt: 'What is the main reason Node.js can handle many concurrent I/O-bound requests efficiently?',
    choices: ['It creates one process per request by default', 'It uses non-blocking I/O with an event loop', 'It stores all data in localStorage', 'It requires TypeScript'],
    correctChoice: 1,
    explanation: 'Node is optimized around non-blocking I/O and callback/event scheduling.',
  },
  {
    id: 'rest-idempotent-put',
    skill: 'REST APIs',
    prompt: 'Which HTTP method is generally expected to be idempotent for replacing or creating a resource at a known URI?',
    choices: ['POST', 'PUT', 'PATCH always', 'CONNECT'],
    correctChoice: 1,
    explanation: 'PUT is designed to be idempotent when setting a resource representation at a known URI.',
  },
  {
    id: 'rest-status-validation-error',
    skill: 'REST APIs',
    prompt: 'Which HTTP status code is a common choice when a JSON request is syntactically valid but fails business validation?',
    choices: ['200', '201', '422', '101'],
    correctChoice: 2,
    explanation: '422 Unprocessable Entity is commonly used for semantic validation failures.',
  },
  {
    id: 'dsa-hashmap-two-sum',
    skill: 'Data Structures and Algorithms',
    prompt: 'For the classic two-sum problem on an unsorted array, which approach usually gives O(n) expected time?',
    choices: ['Nested loops', 'Sort and binary search only', 'A hash map from value to index', 'A stack of previous indexes'],
    correctChoice: 2,
    explanation: 'A hash map can check complements in expected constant time while scanning once.',
  },
  {
    id: 'dsa-bfs-shortest-path',
    skill: 'Data Structures and Algorithms',
    prompt: 'Which algorithm finds the shortest path by number of edges in an unweighted graph?',
    choices: ['Depth-first search', 'Breadth-first search', 'Quick sort', 'Binary search'],
    correctChoice: 1,
    explanation: 'BFS explores by distance layers and finds shortest paths in unweighted graphs.',
  },
  {
    id: 'postgres-index-tradeoff',
    skill: 'PostgreSQL',
    prompt: 'What is a major tradeoff of adding an index to a frequently updated PostgreSQL table?',
    choices: ['Reads may improve, but writes and storage cost increase', 'Writes always become faster', 'Storage cost becomes zero', 'The table stops supporting joins'],
    correctChoice: 0,
    explanation: 'Indexes can speed reads but require extra storage and maintenance on inserts, updates, and deletes.',
  },
  {
    id: 'postgres-transaction-atomicity',
    skill: 'PostgreSQL',
    prompt: 'Why would you wrap an order creation and inventory decrement in a transaction?',
    choices: ['To make CSS atomic', 'To ensure both database changes commit or both roll back', 'To skip constraints', 'To avoid writing SQL'],
    correctChoice: 1,
    explanation: 'Transactions protect consistency by committing all related changes together or rolling them back together.',
  },
  {
    id: 'mongodb-embed-vs-reference',
    skill: 'MongoDB',
    prompt: 'When is embedding documents in MongoDB usually a good fit?',
    choices: ['For bounded child data commonly read with the parent', 'For unbounded audit logs inside one document forever', 'Only when SQL joins are required', 'Never for nested data'],
    correctChoice: 0,
    explanation: 'Embedding works well for bounded, related data that is usually fetched with its parent.',
  },
  {
    id: 'mongodb-index-query-pattern',
    skill: 'MongoDB',
    prompt: 'What should primarily guide index design in MongoDB?',
    choices: ['Alphabetical collection names', 'Common query filters and sort patterns', 'The number of comments in code', 'The frontend framework'],
    correctChoice: 1,
    explanation: 'Indexes should match the fields and ordering used by important query patterns.',
  },
  {
    id: 'git-env-unstage',
    skill: 'Git',
    prompt: 'A .env file was accidentally staged but not committed. What is the correct immediate action?',
    choices: ['Push it and delete later', 'Unstage it and ensure .env is ignored', 'Rename the repository', 'Commit it with a warning'],
    correctChoice: 1,
    explanation: 'Secrets should be removed from the index before commit and covered by .gitignore.',
  },
  {
    id: 'git-rebase-vs-merge',
    skill: 'Git',
    prompt: 'Why might a team prefer rebasing a feature branch before opening a pull request?',
    choices: ['To rewrite the main branch on the remote', 'To replay feature commits on the latest base and simplify review history', 'To delete all conflicts automatically', 'To skip tests'],
    correctChoice: 1,
    explanation: 'Rebasing can put feature commits on the latest base, producing a cleaner review history when used carefully.',
  },
];

export function buildDeterministicSkillAssessment() {
  return DETERMINISTIC_SKILL_ITEMS.map((item) => ({ ...item, choices: [...item.choices] }));
}

export function publicSkillAssessmentItems(items) {
  return items.map(({ correctChoice, explanation, ...item }) => item);
}
