import { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, ChartBar, CheckCircle, Clock, House, ListChecks, SignOut, UserCircle, Path, ArrowClockwise } from '@phosphor-icons/react';
import { SkillPathLogo } from '../components/SkillPathLogo';
import { generateLearning, getLearning, type LearningOverview, type LearningLesson, type LoginResponse, type SkillEvidence } from '../api/skillpathApi';
import { LearningSessionPage } from './LearningSessionPage';
import type { ProfileSetupResult } from './ProfileSetupPage';
import '../workspace.css';

type View = 'home' | 'assessments' | 'roadmap' | 'progress' | 'profile';
const skills = ['HTML','CSS','JavaScript','TypeScript','React','Node.js','REST APIs','Data Structures and Algorithms','PostgreSQL','MongoDB','Git'];
const nav = [{ id:'home', label:'Overview', Icon:House },{ id:'assessments', label:'Assessments & results', Icon:ListChecks },{ id:'roadmap', label:'Learning plan', Icon:Path },{ id:'progress', label:'Learning progress', Icon:ChartBar },{ id:'profile', label:'My profile', Icon:UserCircle }] as const;

export function WorkspacePage({ profile, candidate, initialView = 'home', onAssessment, onProfile, onSignOut }: { profile: ProfileSetupResult; candidate: LoginResponse['candidate'] | null; initialView?: View; onAssessment: () => void; onProfile: () => void; onSignOut: () => void }) {
  const [view, setView] = useState<View>(initialView);
  const [learning, setLearning] = useState<LearningOverview | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [lesson, setLesson] = useState<LearningLesson | null>(null);
  async function refresh() { setLoading(true); setError(''); try { setLearning(await getLearning()); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load learning progress.'); } finally { setLoading(false); } }
  useEffect(() => { let active = true; getLearning().then(data => { if(active) setLearning(data); }).catch(e => { if(active) setError(e.message); }).finally(() => { if(active) setLoading(false); }); return () => { active = false; }; }, []);
  async function generate() { if(busy) return; setBusy(true); setError(''); try { setLearning(await generateLearning()); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to generate your plan.'); } finally { setBusy(false); } }
  const plan = learning?.plan;
  const history = candidate?.assessmentHistory || [];
  const evidence: SkillEvidence[] = candidate?.skillEvidence || plan?.evidence || skills.map(skill => ({ skill, mcq:null, chat:null, score:null, questions:0, skippable:false, status:'Not assessed' }));
  const lessons = plan?.topics.flatMap(topic => topic.sessions) || [];
  const done = new Set(plan?.completed.map(item => item.lesson_id) || []);
  const nextLesson = lessons.find(item => !done.has(item.id));
  const passed = history.filter(item => ['completed','submitted'].includes(item.status));
  const percent = lessons.length ? Math.round(done.size / lessons.length * 100) : plan ? 100 : 0;
  const mcqDone = Boolean(candidate?.latestResult);
  const chatDone = history.some(item => item.type === 'chatbot' && item.status === 'completed');
  const canGenerate = mcqDone && (chatDone || !profile.claimedSkills.length);
  if (lesson && plan) return <LearningSessionPage lesson={lesson} planId={plan.id} readOnly={done.has(lesson.id)} onBack={() => { setLesson(null); void refresh(); }} />;
  const openNext = () => nextLesson ? setLesson(nextLesson) : setView('roadmap');
  return <div className="workspace">
    <aside className="workspace-nav"><SkillPathLogo /><nav aria-label="Workspace">{nav.map(({id,label,Icon}) => <button key={id} className={view === id ? 'active' : ''} aria-current={view === id ? 'page' : undefined} onClick={() => setView(id)}><Icon size={20} />{label}</button>)}</nav><div className="nav-profile"><span className="avatar">{profile.name.slice(0,1).toUpperCase()}</span><div><strong>{profile.name}</strong><small>{profile.domain}</small></div></div><button className="sp-btn-ghost signout" onClick={onSignOut}><SignOut size={18} />Sign out</button></aside>
    <main className="workspace-main">
      <header className="workspace-top"><span>Full Stack Engineering</span><span className="sp-tag">{profile.interestedRoles[0] || 'Learning workspace'}</span></header>
      <div className="workspace-body">
        <header className="page-title"><div><h1>{view === 'home' ? `Welcome back, ${profile.name.split(' ')[0]}` : nav.find(item => item.id === view)?.label}</h1><p>{view === 'home' ? 'Your assessments, priorities, and next learning session in one place.' : view === 'roadmap' ? 'A study plan based on your individual skill results.' : view === 'assessments' ? 'Review your evidence and identify what to practice next.' : view === 'progress' ? 'Completed sessions are saved. Interrupted sessions restart from the beginning.' : 'Your account, education, and learning preferences.'}</p></div><button className="sp-btn-ghost" title="Refresh learning data" aria-label="Refresh learning data" disabled={loading} onClick={() => void refresh()}><ArrowClockwise size={20} /></button></header>
        {error && <div className="sp-notice sp-notice-danger" role="alert">{error}</div>}
        {loading && <p role="status">Loading saved learning progress...</p>}
        {view === 'home' && <>
          <div className="stat-strip">{[{label:'Knowledge assessment',value:mcqDone ? `${candidate?.latestResult?.score}%` : 'Not taken',note:mcqDone ? `${candidate?.latestResult?.correct_count} correct answers` : 'Establish your starting point',Icon:ListChecks},{label:'Interview',value:chatDone ? 'Completed' : profile.claimedSkills.length ? 'Not taken' : 'Not required',note:`${profile.claimedSkills.length} skills in your profile`,Icon:CheckCircle},{label:'Learning sessions',value:`${done.size} / ${lessons.length}`,note:plan ? `${percent}% of your plan complete` : 'Plan available after assessment',Icon:BookOpen},{label:'Study time remaining',value:plan ? `${(lessons.length-done.size)*10} min` : 'Not estimated',note:'Ten-minute focused sessions',Icon:Clock}].map(({label,value,note,Icon}) => <article key={label}><div><span>{label}</span><Icon size={20} /></div><strong>{value}</strong><small>{note}</small></article>)}</div>
          <section className="next-action"><div><h2>{nextLesson ? 'Continue your learning' : plan ? 'Your learning plan' : mcqDone ? 'Turn your results into a study plan' : 'Start with your skill assessment'}</h2><p>{nextLesson ? nextLesson.title : plan ? 'Review your completed sessions and optional revision topics.' : mcqDone ? 'Review your per-skill evidence and generate focused learning sessions.' : 'Complete a technical interview for your claimed skills, then a knowledge assessment across the full stack.'}</p></div><button className="sp-btn-primary" onClick={plan ? openNext : mcqDone ? () => setView('roadmap') : onAssessment}>{nextLesson ? 'Continue learning' : plan ? 'View plan' : mcqDone ? 'Create learning plan' : 'Prepare for assessment'}<ArrowRight size={18} /></button></section>
          <div className="workspace-columns"><section><SectionTitle title="Your skill profile" /><SkillTable evidence={evidence} /></section><section><SectionTitle title="Your next steps" /><ol className="journey-list">{[{title:'Complete your profile',detail:profile.interestedRoles.join(', '),complete:true},{title:'Technical interview',detail:profile.claimedSkills.length ? 'Evaluate your claimed skills' : 'Not required without claimed skills',complete:chatDone || !profile.claimedSkills.length},{title:'Knowledge assessment',detail:'Full Stack Engineering fundamentals',complete:mcqDone},{title:'Personal learning plan',detail:'Focused ten-minute sessions',complete:Boolean(plan)}].map((item,i) => <li key={item.title}><span className={item.complete ? 'journey-number complete' : 'journey-number'}>{item.complete ? <CheckCircle size={19} /> : i+1}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div></li>)}</ol><SectionTitle title="Recent activity" /><Activity history={history.slice(0,4)} /></section></div>
        </>}
        {view === 'assessments' && <><div className="assessment-options"><article><ListChecks size={26} /><h2>Technical interview</h2><p>Short written answers on your claimed skills. Each skill is evaluated separately.</p><span className="sp-tag">{chatDone ? 'Completed' : profile.claimedSkills.length ? 'Ready to assess' : 'Not required'}</span></article><article><ChartBar size={26} /><h2>Knowledge assessment</h2><p>One question at a time across eleven Full Stack Engineering skills.</p><span className="sp-tag">{mcqDone ? `${candidate?.latestResult?.score}% overall` : 'Not started'}</span></article></div><div className="section-title"><h2>Per-skill results</h2><button className="sp-btn-primary" onClick={onAssessment}>{mcqDone ? 'Retake assessment' : 'Prepare for assessment'}<ArrowRight size={18} /></button></div><p className="table-note">Combined score: 60% knowledge assessment and 40% interview where both are available. Optional review requires at least 80% in each available assessment; this is not a mastery certification.</p><SkillTable evidence={evidence} /><SectionTitle title="Assessment history" /><Activity history={history} /></>}
        {view === 'roadmap' && <>
          {plan && learning?.needsRefresh && <section className="next-action"><div><h2>New assessment results available</h2><p>Your saved plan uses an earlier assessment. Updating creates a new plan; previous completions remain stored with the previous plan.</p></div><button className="sp-btn-primary" disabled={busy} onClick={()=>void generate()}>{busy?'Updating...':'Update learning plan'}<ArrowRight size={18} /></button></section>}
          {!plan ? <section className="plan-start"><div><h2>{canGenerate ? 'Your results are ready' : 'Complete your assessments first'}</h2><p>{canGenerate ? 'Generate a saved study plan with topics, practical exercises, checkpoint questions, and ten-minute sessions.' : 'Your plan uses real assessment evidence. Complete the required assessment stages to identify your strengths and learning needs.'}</p><div className="action-row"><button className="sp-btn-primary" disabled={busy || loading} onClick={canGenerate ? () => void generate() : onAssessment}>{busy ? 'Creating your plan...' : canGenerate ? 'Generate learning plan' : 'Prepare for assessment'}<ArrowRight size={18} /></button></div>{canGenerate && <small>Only anonymous skill scores are sent to the learning provider. A full plan can take several minutes. Keep this page open.</small>}</div><div><h3>Assessment coverage</h3><SkillTable evidence={evidence} compact /></div></section> : <><div className="plan-summary"><div><strong>{plan.topics.length}</strong><span>Priority topics</span></div><div><strong>{lessons.length}</strong><span>Ten-minute sessions</span></div><div><strong>{plan.estimatedMinutes} min</strong><span>Estimated study time</span></div><div><strong>{done.size}</strong><span>Sessions completed</span></div></div><div className="sp-progress" aria-label={`${percent}% complete`}><div className="sp-progress-fill" style={{width:`${percent}%`}} /></div>{plan.topics.map((topic,i) => <section className="roadmap-topic" key={topic.id}><div className="topic-heading"><span className="topic-number">{String(i+1).padStart(2,'0')}</span><div><h2>{topic.skill}</h2><p>{topic.reason}</p></div><span>{topic.sessions.length*10} min</span></div><div className="lesson-list">{topic.sessions.map(item => <article key={item.id}><div>{done.has(item.id) ? <CheckCircle size={22} /> : <BookOpen size={22} />}<div><h3>{item.title}</h3><p>{item.objective}</p></div></div><button className="sp-btn-secondary" onClick={() => setLesson(item)}>{done.has(item.id) ? 'Review session' : 'Start session'}{!done.has(item.id) && <ArrowRight size={17} />}</button></article>)}</div></section>)}<SectionTitle title="Optional review" /><p className="table-note">These skills met the review threshold in the available assessments. You can skip them in this plan; limited question coverage is not proof of complete mastery.</p><div className="skill-tags">{plan.evidence.filter(s => s.skippable).map(s => <span className="sp-tag sp-tag-accent" key={s.skill}><CheckCircle size={16} />{s.skill}</span>)}{!plan.evidence.some(s => s.skippable) && <p>No skills currently meet the optional-review threshold.</p>}</div></>}
        </>}
        {view === 'progress' && <><div className="plan-summary"><div><strong>{percent}%</strong><span>Learning plan complete</span></div><div><strong>{done.size*10} min</strong><span>Completed study time</span></div><div><strong>{passed.length}</strong><span>Completed assessments</span></div></div><SectionTitle title="Topic progress" />{plan?.topics.map(topic => { const count=topic.sessions.filter(s=>done.has(s.id)).length; return <div className="progress-row" key={topic.id}><h3>{topic.skill}</h3><div className="sp-progress"><div className="sp-progress-fill" style={{width:`${count/topic.sessions.length*100}%`}} /></div><span>{count} / {topic.sessions.length}</span></div>; })}{!plan && <section className="next-action"><p>Your topic progress will appear once you create a learning plan.</p><button className="sp-btn-primary" onClick={() => setView('roadmap')}>Open learning plan <ArrowRight size={18} /></button></section>}<SectionTitle title="Completed learning sessions" />{plan?.completed.map(item => <div className="activity-row" key={item.lesson_id}><CheckCircle size={20} /><strong>{lessons.find(l=>l.id===item.lesson_id)?.title}</strong><time>{new Date(item.completed_at).toLocaleString()}</time><span>10 min</span></div>)}{!done.size && <p className="table-note">No completed learning sessions yet.</p>}<SectionTitle title="Assessment activity" /><Activity history={history} /></>}
        {view === 'profile' && <div className="workspace-columns"><section><SectionTitle title="Account details" /><dl className="profile-details">{[['Name',profile.name],['Email',profile.email],['Email verification',candidate?.emailVerified?'Verified':'Not verified'],['Qualification',profile.qualification],['Learning domain',profile.domain],['Institution',(profile.setup?.collegeName === 'Other' ? profile.setup?.customCollegeName : profile.setup?.collegeName) || 'Not provided']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><button className="sp-btn-primary" onClick={onProfile}>Edit profile <ArrowRight size={18} /></button></section><section><SectionTitle title="Target roles" /><div className="skill-tags">{profile.interestedRoles.map(role=><span key={role} className="sp-tag sp-tag-blue">{role}</span>)}</div><SectionTitle title="Claimed skills" /><div className="skill-tags">{profile.claimedSkills.map(skill=><span key={skill} className="sp-tag">{skill}</span>)}{!profile.claimedSkills.length && <p>No prior skills claimed.</p>}</div><p className="table-note">Claimed skills are self-reported. Assessment results provide a separate measure of your current knowledge.</p></section></div>}
      </div>
    </main>
  </div>;
}
function SectionTitle({title}:{title:string}) { return <div className="section-title"><h2>{title}</h2></div>; }
function SkillTable({evidence,compact=false}:{evidence:SkillEvidence[];compact?:boolean}) { return <div className="table-scroll"><table className="skill-table"><thead><tr><th>Skill</th>{!compact && <><th>Knowledge</th><th>Interview</th></>}<th>{compact?'Result':'Combined'}</th><th>Next step</th></tr></thead><tbody>{evidence.map(s=><tr key={s.skill}><th scope="row">{s.skill}</th>{!compact && <><td>{s.mcq===null?'Not assessed':`${s.mcq}%`}</td><td>{s.chat===null?'Not assessed':`${s.chat}%`}</td></>}<td>{s.score===null?'Not assessed':`${s.score}%`}</td><td><span className={`sp-tag ${s.skippable?'sp-tag-accent':''}`}>{s.status}</span></td></tr>)}</tbody></table></div>; }
function Activity({history}:{history:LoginResponse['candidate']['assessmentHistory']}) { return <div>{history.length ? history.map(item=><div className="activity-row" key={item.id}><ListChecks size={18} /><div><strong>{item.type==='chatbot'?'Technical interview':'Knowledge assessment'}</strong><small>{item.status}</small></div><time>{new Date(item.createdAt).toLocaleDateString()}</time><span>{item.score!=null?`${item.score}%`:item.aggregate?`${item.aggregate.score}%`:'No score'}</span></div>) : <p className="table-note">No assessment activity yet. Your completed and interrupted attempts will appear here.</p>}</div>; }
