import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { PDFDocument } from 'pdf-lib';

await mkdir('screenshots', { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage', '--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream', '--auto-select-desktop-capture-source=Entire screen', '--allow-http-screen-capture', '--enable-usermedia-screen-capturing'] });
const mobileRun = process.env.TEST_VIEWPORT === 'mobile';
const context = await browser.newContext({ viewport: mobileRun ? { width: 390, height: 844 } : { width: 1440, height: 1000 }, permissions: ['camera', 'microphone'] });
const page = await context.newPage();
page.setDefaultTimeout(30000);
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const captures = [];
async function screenshot(name) {
  await page.screenshot({ path: `screenshots/${name}-${mobileRun ? 'mobile' : 'desktop'}.png`, fullPage: true });
  captures.push(name);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), `${name} overflows`);
}
const username = `browser${Date.now()}`;
const password = 'BrowserPassword123!';
try {
  await page.goto('http://localhost:5173');
  await page.getByRole('heading', { name: 'Welcome back' }).waitFor();
  await screenshot('01-login');
  await page.getByRole('tab', { name: 'Sign up' }).click();
  await page.getByLabel('Username', { exact: true }).fill(username);
  await page.getByLabel('Email', { exact: true }).fill(`${username}@example.com`);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await screenshot('02-signup');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await page.getByRole('heading', { name: 'Profile setup', exact: true }).waitFor();
  await page.getByLabel('First name').fill('Jordan');
  await page.getByLabel('Last name').fill('Taylor');
  await page.getByLabel('Age', { exact: true }).fill('24');
  await page.getByLabel('College name', { exact: true }).selectOption('Vellore Institute of Technology');
  await page.getByLabel('College city').selectOption('Bengaluru');
  await page.getByLabel('CGPA').fill('8.4');
  await page.getByLabel('Start year').selectOption('2021');
  await page.getByLabel('End year').selectOption('2025');
  await page.getByRole('button', { name: 'Associate Software Engineer', exact: true }).click();
  await page.getByRole('button', { name: 'React', exact: true }).click();
  await page.locator('input[type=file]').first().setInputFiles({ name: 'invalid.docx', mimeType: 'application/octet-stream', buffer: Buffer.from('invalid') });
  await page.getByRole('alert').filter({ hasText: 'valid PDF' }).waitFor();
  await screenshot('03-pdf-validation');
  const pdf = await PDFDocument.create(); pdf.addPage();
  await page.locator('input[type=file]').first().setInputFiles({ name: 'resume.pdf', mimeType: 'application/pdf', buffer: Buffer.from(await pdf.save()) });
  await page.getByText('resume.pdf', { exact: true }).waitFor();
  await screenshot('04-profile');
  await page.getByRole('button', { name: 'Review profile', exact: true }).click();
  await screenshot('05-profile-review');
  await page.getByRole('button', { name: 'Submit', exact: true }).click();
  await page.getByRole('button', { name: 'Continue to dashboard', exact: true }).click();
  await page.getByRole('heading', { name: 'Learning Gap Engine' }).waitFor();
  await screenshot('06-dashboard');
  await page.reload();
  await page.getByRole('heading', { name: 'Learning Gap Engine' }).waitFor();
  await page.getByRole('link', { name: 'Profile', exact: true }).click();
  assert.equal(await page.getByLabel('Age', { exact: true }).inputValue(), '24');
  assert.equal(await page.getByLabel('CGPA').inputValue(), '8.4');
  await page.reload();
  await page.getByRole('button', { name: 'Start assessment', exact: true }).click();
  const rules = page.getByRole('checkbox');
  for (let i = 0; i < await rules.count(); i++) await rules.nth(i).click();
  await screenshot('07-guidelines');
  await page.getByRole('button', { name: 'Request access and start', exact: true }).click();
  await page.locator('textarea').waitFor({ timeout: 60000 });
  if (!mobileRun) await page.waitForFunction(() => [...document.querySelectorAll('video')].some(video => video.videoWidth > 0 && !video.paused));
  await screenshot('08-chatbot-camera');
  await page.locator('textarea').fill('I do not know the answer.');
  await page.getByRole('button', { name: 'Submit answer', exact: true }).click();
  await page.getByRole('button', { name: 'Continue to skill assessment', exact: true }).waitFor({ timeout: 60000 });
  await screenshot('09-chatbot-result');
  await page.getByRole('button', { name: 'Continue to skill assessment', exact: true }).click();
  await page.getByRole('button', { name: 'Submit deterministic assessment', exact: true }).waitFor();
  if (!mobileRun) await page.waitForFunction(() => [...document.querySelectorAll('video')].some(video => video.videoWidth > 0 && !video.paused));
  await screenshot('10-deterministic-camera');
  const cards = page.locator('article');
  for (let i = 0; i < await cards.count(); i++) await cards.nth(i).getByRole('button').first().click();
  await page.getByRole('button', { name: 'Submit deterministic assessment', exact: true }).click();
  await page.getByRole('button', { name: 'Continue to gap analysis' }).waitFor();
  await screenshot('11-deterministic-results');
  await page.getByRole('button', { name: 'Continue to gap analysis' }).click();
  await page.getByRole('heading', { name: 'Gap Detection and Learning Roadmap' }).waitFor();
  await screenshot('12-learning-roadmap');
  await page.reload();
  await page.getByRole('heading', { name: 'Learning Gap Engine' }).waitFor();
  await page.getByRole('link', { name: 'Assessments', exact: true }).click();
  await page.getByText(/Latest deterministic result:/).waitFor();
  await screenshot('13-returning-dashboard');
  assert.deepEqual(errors, []);
  await writeFile(`screenshots/browser-results-${mobileRun ? 'mobile' : 'desktop'}.json`, JSON.stringify({ passed: true, captures, media: 'Chromium simulated camera and screen', ai: process.env.ALLOW_DETERMINISTIC_AI_FALLBACK === 'true' ? 'Deterministic fallback enabled for local verification' : 'Live configured Gemini SDK', checks: ['signup', 'PDF content validation', 'profile persistence', 'session restore', 'camera playback', 'chatbot progression', 'deterministic scoring', 'results restore', 'responsive overflow', 'no runtime page errors'] }, null, 2));
  await rm('screenshots/browser-failure.png', { force: true });
  console.log('Browser workflow passed:', captures.join(', '));
} catch (error) {
  await page.screenshot({ path: 'screenshots/browser-failure.png', fullPage: true });
  console.error(await page.locator('body').innerText());
  throw error;
} finally { await browser.close(); }
